Repository LLNL/conduit, pull requests merged in 2018-07, with the labels that each got.

#310 fix bug in std::vect gap methods and add more tests
  src/libs/conduit/conduit_node.cpp
  src/tests/conduit/t_conduit_node_set.cpp
Labels: bug

#197 add mesh topology transformations to blueprint
  src/libs/blueprint/conduit_blueprint_mesh.cpp
  src/libs/blueprint/conduit_blueprint_mesh.hpp
  src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
  src/libs/conduit/conduit_data_type.hpp
  src/libs/conduit/conduit_node.cpp
  src/libs/conduit/conduit_node.hpp
  src/libs/conduit/conduit_schema.cpp
  src/libs/conduit/conduit_schema.hpp
  src/tests/blueprint/CMakeLists.txt
  src/tests/blueprint/t_blueprint_mesh_transform.cpp
  src/tests/blueprint/t_blueprint_mesh_verify.cpp
  src/tests/conduit/CMakeLists.txt
  src/tests/conduit/t_conduit_datatype_tests.cpp
  src/tests/conduit/t_conduit_node_to_array.cpp
  src/tests/conduit/t_conduit_node_to_value.cpp
Labels: feature

#313 a few relay io hdf5 enhancements
  src/libs/conduit/conduit_utils.cpp
  src/libs/conduit/conduit_utils.hpp
  src/libs/conduit/python/conduit_python.cpp
  src/libs/relay/CMakeLists.txt
  src/libs/relay/conduit_relay_io.cpp
  src/libs/relay/conduit_relay_io.hpp
  src/libs/relay/conduit_relay_io_convert_exe.cpp
  src/libs/relay/python/conduit_relay_io_python.cpp
  src/tests/relay/CMakeLists.txt
  src/tests/relay/python/t_python_relay_io.py
  src/tests/relay/t_relay_io_file_sizes.cpp
  src/tests/relay/t_relay_io_hdf5.cpp
Labels: feature

#314 relay python io: expose save_merged and load_merged
  src/libs/conduit/python/conduit_python.cpp
  src/libs/relay/conduit_relay_io.cpp
  src/libs/relay/python/conduit_relay_io_python.cpp
  src/tests/relay/python/t_python_relay_io.py
Labels: task

#316 relay mpi send w schema bugfix for compact but not contig
  src/libs/relay/conduit_relay_mpi.cpp
  src/tests/relay/t_relay_mpi_test.cpp
Labels: bug

#317 relay io py: catch relay io excepts and foward to python
  src/libs/relay/python/conduit_relay_io_python.cpp
  src/tests/relay/python/t_python_relay_io.py
Labels: task

#319 uber updates
  appveyor.yml
  scripts/uberenv/project.json
  scripts/uberenv/spack_configs/blueos_3_ppc64le_ib/packages.yaml
  scripts/uberenv/uberenv.py
  src/tests/conduit/t_conduit_node_set.cpp
Labels: task

#320 relay io: add method to list an hdf5 group's child names
  src/libs/relay/conduit_relay_hdf5.cpp
  src/libs/relay/conduit_relay_hdf5.hpp
  src/tests/relay/t_relay_io_hdf5.cpp
Labels: feature
