Repository LLNL/conduit, pull requests merged in 2019-07, with the labels that each got.

#429 add spack + uber support for building zfp as conduit dep
  .travis.yml
  scripts/uberenv/packages/conduit/package.py
  scripts/uberenv/packages/zfpcmake/package.py
Labels: task

#432 memcheck pass
  CHANGELOG.md
  src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
  src/libs/conduit/conduit_node.cpp
  src/tests/blueprint/t_blueprint_mesh_examples.cpp
  src/tests/blueprint/t_blueprint_mesh_transform.cpp
  src/tests/conduit/c/t_c_conduit_node.cpp
  src/tests/conduit/t_conduit_node.cpp
Labels: bug

#431 add specsets validation and testing
  CHANGELOG.md
  src/docs/sphinx/blueprint_mesh.rst
  src/libs/blueprint/conduit_blueprint_mcarray.cpp
  src/libs/blueprint/conduit_blueprint_mcarray.hpp
  src/libs/blueprint/conduit_blueprint_mesh.cpp
  src/libs/blueprint/conduit_blueprint_mesh.hpp
  src/libs/blueprint/conduit_blueprint_mesh_examples.cpp
  src/tests/blueprint/t_blueprint_mesh_verify.cpp
Labels: feature, task
